blog/urls.py
from django.conf.urls import url
from . import views
from django.core.urlresolvers import reverse
from django.views.generic.base import TemplateView

app_name = 'blog'

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^sraban/$', views.sraban, name='sraban'),
    url(r'^profile/$',TemplateView.as_view(template_name = 'blog/profile.html'), name="profile"),
    url(r'^saved/$', views.SaveProfile, name = 'saved'),
    url(r'^updated/(?P<pk>.*)/$', views.EditProfile, name = 'updated'),
    url(r'^email/(?P<pk>.*)/$', views.emailProfile, name = 'email'),
]

study/urls.py
from django.conf.urls import *
from django.contrib import admin

from django.views.generic.base import TemplateView

urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name='index.html'), name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls') ),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Profile(models.Model):
   name = models.CharField(max_length = 50)
   email = models.CharField(max_length = 50)
   #picture = models.FileField(upload_to = 'pictures') #ImageField
   #document = models.FileField(upload_to = 'documents') #docs
   age = models.IntegerField()
   picture = models.CharField(max_length = 255)
   document = models.TextField(max_length = 255)
   city = models.CharField(max_length = 255)
   gender = models.CharField(max_length = 255)
   banks = models.CharField(max_length = 255)
   summary = models.TextField(max_length = 255)
   banks = models.TextField(max_length = 255)

   def banks_as_list(self):
        return self.banks.split(',')

   def document_as_list(self):
   		return self.document.split(',')

   class Meta:
      db_table = "profile"

blog/forms.py
#-*- coding: utf-8 -*-
from django import forms
from blog.models import Profile

class ProfileForm(forms.Form):
   name = forms.CharField(max_length = 50)
   email = forms.EmailField(max_length = 50)
   #picture = forms.FileField()
   #documents = forms.FileField()

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core import serializers
import requests
import json
import os
import time
import datetime

from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect

from blog.models import Profile
from blog.forms import ProfileForm
from django.conf import settings

# Create your views here.
def sraban(request):
	data = requests.get('https://sraban.000webhostapp.com/')
	return HttpResponse(data)

def save_file(file, path):
    ''' Little helper to save a file '''
    fd = open('%s/%s' % (settings.MEDIA_ROOT, str(path)), 'wb')
    for chunk in file.chunks():
        fd.write(chunk)
    fd.close()
    return True

def emailProfile(request, pk):

   detail = Profile.objects.get( pk = pk )
   html_content = render(request,'blog/email_profile.html', locals())
   html_content = str(html_content).replace('Content-Type: text/html; charset=utf-8','').replace('\n','')
   emailto = detail.email
   email = EmailMessage("my subject", html_content, "from@edkal.com", [emailto])
   email.content_subtype = "html"
   res = email.send()
   return HttpResponse('%s'%res)

def index(request):
   deleted = False
   detail = Profile.objects.all()
   if request.method == "POST":
   	if 'delete_id' in request.POST:
   	 delete_id = request.POST['delete_id']
        try:
         Profile.objects.get( pk = delete_id ).delete()
         deleted = True
        except Profile.DoesNotExist:
         deleted = False
   return render(request, 'blog/list_profile.html', locals())

def SaveProfile(request):
   
   saved = False
   document_files = []

   if request.method == "POST":
   	
      MyProfileForm = ProfileForm(request.POST, request.FILES)
      
      if MyProfileForm.is_valid():
         profile = Profile() 
         #MyProfileForm.cleaned_data["agree"]
         #profile.picture = MyProfileForm.cleaned_data["picture"]
         if 'name' in request.POST:
         	profile.name = MyProfileForm.cleaned_data["name"]
         if 'email' in request.POST:
         	profile.email = MyProfileForm.cleaned_data["email"]
         if 'city' in request.POST:
         	profile.city = request.POST["city"]
         if 'gender' in request.POST:
         	profile.gender = request.POST["gender"]
         if 'age' in request.POST:
         	profile.age = request.POST["age"]
         if 'summary' in request.POST:
         	profile.summary = request.POST["summary"]
         
         if 'picture' in request.FILES:
         	ts = time.time()
         	pic_name = datetime.datetime.fromtimestamp(ts).strftime('%Y_%m_%d_%H_%M_%S_') + request.FILES['picture']._get_name()
         	pic_name = 'static/pictures/' + pic_name.replace(' ', '_').lower()
         	if save_file(request.FILES['picture'], pic_name):
         		profile.picture = pic_name

         if 'documents' in request.FILES:
            ts = time.time()
            for document in request.FILES.getlist('documents'):
             document_file = datetime.datetime.fromtimestamp(ts).strftime('%Y_%m_%d_%H_%M_%S_') + document._get_name()
             document_file = 'static/documents/' + document_file.replace(' ', '_').lower()
             if save_file(document, document_file):
              document_files.append(document_file)
            if len(document_files) > 0:
             profile.document = ','.join(document_files)
            
         if request.POST.has_key('bank'):
            profile.banks = ','.join(request.POST.getlist('bank')) 
         
         profile.save()
         saved = True
   else:
      MyProfileForm = ProfileForm()
	
   #return HttpResponse(profile.document)
   #return HttpResponse(json.dumps(request.POST))
   #return HttpResponseRedirect('/thanks/') # Redirect
   return render(request, 'blog/profile.html', locals())


def EditProfile(request, pk):
   document_files = []
   detail = Profile.objects.get( pk = pk )
   saved = False
   if request.method == "POST":

      MyProfileForm = ProfileForm(request.POST, request.FILES)
      
      if MyProfileForm.is_valid():
         #MyProfileForm.cleaned_data["agree"]
         #profile.picture = MyProfileForm.cleaned_data["picture"]
         if 'name' in request.POST:
         	detail.name = MyProfileForm.cleaned_data["name"]
         if 'email' in request.POST:
         	detail.email = MyProfileForm.cleaned_data["email"]
         if 'city' in request.POST:
         	detail.city = request.POST["city"]
         if 'gender' in request.POST:
         	detail.gender = request.POST["gender"]
         if 'age' in request.POST:
         	detail.age = request.POST["age"]
         if 'summary' in request.POST:
         	detail.summary = request.POST["summary"]
         
         if 'picture' in request.FILES:
         	ts = time.time()
         	pic_name = datetime.datetime.fromtimestamp(ts).strftime('%Y_%m_%d_%H_%M_%S_') + request.FILES['picture']._get_name()
         	pic_name = 'static/pictures/' + pic_name.replace(' ', '_').lower()
         	if save_file(request.FILES['picture'], pic_name):
         		detail.picture = pic_name

         if 'documents' in request.FILES:
            ts = time.time()
            for document in request.FILES.getlist('documents'):
             document_file = datetime.datetime.fromtimestamp(ts).strftime('%Y_%m_%d_%H_%M_%S_') + document._get_name()
             document_file = 'static/documents/' + document_file.replace(' ', '_').lower()
             if save_file(document, document_file):
              document_files.append(document_file)
            if len(document_files) > 0:
             detail.document = ','.join(document_files)

         if request.POST.has_key('bank'):
            detail.banks = ','.join(request.POST.getlist('bank')) 

         detail.save()
         saved = True
   else:
      MyProfileForm = ProfileForm()
	
   #return HttpResponse(detail.city)
   #return HttpResponse(json.dumps(document_files))
   #return HttpResponseRedirect('/thanks/') # Redirect
   return render(request, 'blog/edit_profile.html', locals())

templates/blog/edit_profile.html
{% extends 'blog/layout.html' %}

{% block title %}Profile Lists{% endblock %}

{% block content %}

		<h1>Register Profile</h1>

		  {% if saved %}
	         <div class="alert alert-success"><strong>Well done!</strong> You are successfully Updated <a href="{% url 'blog:index' %}">Go Back</a></div>
	      {% endif %}
	      

			<form class="needs-validation" novalidate  method="POST" action="{% url 'blog:updated' pk %}" accept-charset="UTF-8" enctype="multipart/form-data">
				{% csrf_token %}
				
				<div class="form-group">
	              <label for="name">Name</label>
	              <input type="text" class="form-control" name="name" value="{{ detail.name }}">
	            </div>

				<div class="form-group">
	              <label for="email">Email address</label>
	              <input type="email" class="form-control" name="email" value="{{ detail.email }}">
	            </div>
	            
				<div class="form-group">
	              <label for="age">Age</label>
	              <input type="text" class="form-control" name="age" value="{{ detail.age }}">
	            </div>

	            <div class="form-group">
	              <label for="city">City</label>
	              <select class="form-control" name="city">
		                <option value="Bangalore" {% if detail.city == 'Bangalore' %}selected{% endif %}>Bangalore</option>
		                <option value="Delhi" {% if detail.city == 'Delhi' %}selected{% endif %}>Delhi</option>
		                <option value="Calcutta" {% if detail.city == 'Calcutta' %}selected{% endif %}>Calcutta</option>
		                <option value="Gowhati" {% if detail.city == 'Gowhati' %}selected{% endif %}>Gowhati</option>
		                <option value="Bhubaneswar" {% if detail.city == 'Bhubaneswar' %}selected{% endif %}>Bhubaneswar</option>
	              </select>
	            </div>
	            <div class="form-group">
	              <label for="bank">Bank Accounts You have</label>
	              <select class="form-control" name="bank" multiple>
	                <option value="SBI" {% if 'SBI' in detail.banks_as_list %} selected {% endif %}>SBI</option>
	                <option value="HDFC" {% if 'HDFC' in detail.banks_as_list %} selected {% endif %}>HDFC</option>
	                <option value="AXIS" {% if 'AXIS' in detail.banks_as_list %} selected {% endif %}>AXIS</option>
	                <option value="IDBI" {% if 'IDBI' in detail.banks_as_list %} selected {% endif %}>IDBI</option>
	                <option value="ICICI" {% if 'ICICI' in detail.banks_as_list %} selected {% endif %}>ICICI</option>
	              </select>
	            </div>

	            <div class="form-group">
	              <label for="picture">Photo Upload</label>
	              <input type="file" name="picture" class="form-control-file">
	              {{ detail.picture }}
	            </div>

	            <div class="form-group">
	              <label for="documents">Document Upload</label>
	              <input type="file" name="documents" class="form-control-file" multiple>
	              {% for doc in detail.document_as_list %}
	              	{{ doc }}<br>
	              {% endfor %}
	            </div>

	            <fieldset class="form-group">
	                <div class="row">
	                  <legend class="col-form-label col-sm-2 pt-0">Gender</legend>
	                  <div class="col-sm-10">
	                    <div class="form-check">
	                      <input class="form-check-input" type="radio" name="gender" value="male" {% if detail.gender == 'male' %} checked {% endif %}>
	                      <label class="form-check-label">
	                        Male
	                      </label>
	                    </div>
	                    <div class="form-check">
	                      <input class="form-check-input" type="radio" name="gender" value="female" {% if detail.gender == 'female' %} checked {% endif %}>
	                      <label class="form-check-label">
	                        Female
	                      </label>
	                    </div>
	                    <div class="form-check disabled">
	                      <input class="form-check-input" type="radio" name="gender" value="both" disabled>
	                      <label class="form-check-label">
	                        Both
	                      </label>
	                    </div>
	                  </div>
	                </div>
	              </fieldset>

	              <div class="form-group">
	                <label for="summary">Summary</label>
	                <textarea class="form-control" name="summary" rows="3">{{ detail.summary }}</textarea>
	              </div>
	            
		          <button type="submit" class="btn btn-primary">Submit</button>
		          <button type="reset" class="btn btn-primary">Reset</button>
			</form>
	{% endblock %}

templates/blog/email_profile.html
{% if detail.picture %}
{% load static %}
<p><img src="{{ detail.picture }}" width="100" alt="My image"></p>
{% endif %}

<p><strong>Name: {{ detail.name }}</strong></p>
<p><strong>Email: {{ detail.email }}</strong></p>
<p><strong>Age: {{ detail.age }}</strong></p>
<p><strong>City: {{ detail.city }}</strong></p>

templates/blog/layout.html
<html>
<head>
	  <title>{% block title %}WebApp in Python!{% endblock %}</title>
      <script type="text/javascript" src="https://code.jquery.com/jquery-git.js"></script>
	  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
      <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
</head>
<body>
	<div class="container">

		<nav class="navbar navbar-inverse">
		    <div class="navbar-header">
		        <a class="navbar-brand" href="{% url 'blog:sraban'%}">Django 1.1</a>
		    </div>
		    <ul class="nav navbar-nav">
		        <li><a href="{% url 'blog:index' %}" class="btn"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> View All Profiles</a></li>
		        <li><a href="{% url 'blog:profile' %}" class="btn"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Register</a>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		        <li><a href=""><span class="glyphicon glyphicon-log-out"></span> logout &nbsp; </a></li>
		    </ul>
		</nav>

		{% block content%}Pages{% endblock %}
		

	</div>
</body>
</html>

templates/blog/list_profile.html
{% extends 'blog/layout.html' %}

{% block title %}Profile Lists{% endblock %}

{% block content %}

		<h1>List of Profile</h1>

		  {% if deleted %}
	         <div class="alert alert-success"><strong>Well done!</strong> You are successfully deleted - {{ delete_id }}</div>
	      {% endif %}
	      
	      <table class="table table-striped table-bordered">
		    <thead>
		        <tr>
		            <td>ID</td>
		            <td>Name</td>
		            <td>Email</td>
		            <td>Age</td>
		            <td>Actions</td>
		        </tr>
		    </thead>
		    <tbody>
		        {% for record in detail %}
		        <tr>
		            <td>{{ record.id }}</td>
		            <td>{{ record.name }}</td>
		            <td>{{ record.email }}</td>
		            <td>20</td>
		            <td width="300">
		                <a href="{% url 'blog:updated' record.id %}" class="btn btn-small a-btn-slide-text">
					        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
					        <span><strong>Edit</strong></span>            
					    </a>
		            	
						<a class="btn btn-small btn-small a-btn-slide-text email" p_id="{% url 'blog:email' record.id %}">
							<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
							<span><strong>Email</strong></span>
						</a>

						<form method="post" action="{% url 'blog:index' %}" class="btn a-btn-slide-text">
			            	{% csrf_token %}
			            	<input type="hidden" name="delete_id" value="{{record.id}}">
							<button class="btn btn-small" type="submit">
								<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
								<span><strong>Delete</strong></span>
							</button>
						</form>

		            </td>
		        </tr>
		        {% endfor %}
		    </tbody>
		</table>
		<script type="text/javascript">
			$(".email").click(function() {
				$p_id = $(this).attr("p_id");
				$.ajax({
					url:$p_id,
					type:"GET",
					success: function() {
						alert("Awesome! Please check your Email");
					}
				});

			});
		</script>
{% endblock %}

templates/blog/profile.html
{% extends 'blog/layout.html' %}

{% block title %}Register a Profile{% endblock %}

{% block content %}

		<h1>Register Profile</h1>

		  {% if saved %}
	         <div class="alert alert-success"><strong>Well done!</strong> You are successfully Registered</div>
	      {% endif %}
	      

			<form class="needs-validation" novalidate  method="POST" action="{% url 'blog:saved' %}" accept-charset="UTF-8" enctype="multipart/form-data">
				{% csrf_token %}
				
				<div class="form-group">
	              <label for="name">Name</label>
	              <input type="text" class="form-control" name="name" placeholder="Sraban">
	            </div>

				<div class="form-group">
	              <label for="email">Email address</label>
	              <input type="email" class="form-control" name="email" placeholder="name@example.com">
	            </div>
	            
				<div class="form-group">
	              <label for="age">Age</label>
	              <input type="text" class="form-control" name="age" placeholder="20">
	            </div>

	            <div class="form-group">
	              <label for="city">City</label>
	              <select class="form-control" name="city">
		                <option value="Bangalore">Bangalore</option>
		                <option value="Delhi">Delhi</option>
		                <option value="Calcutta">Calcutta</option>
		                <option value="Gowhati">Gowhati</option>
		                <option value="Bhubaneswar">Bhubaneswar</option>
	              </select>
	            </div>
	            <div class="form-group">
	              <label for="bank">Bank Accounts You have</label>
	              <select class="form-control" name="bank" multiple>
	                <option value="SBI">SBI</option>
	                <option value="HDFC">HDFC</option>
	                <option value="AXIS">AXIS</option>
	                <option value="IDBI">IDBI</option>
	                <option value="ICICI">ICICI</option>
	              </select>
	            </div>

	            <div class="form-group">
	              <label for="picture">Photo Upload</label>
	              <input type="file" name="picture" class="form-control-file">
	            </div>

	            <div class="form-group">
	              <label for="documents">Document Upload</label>
	              <input type="file" name="documents" class="form-control-file" multiple>
	            </div>

	            <fieldset class="form-group">
	                <div class="row">
	                  <legend class="col-form-label col-sm-2 pt-0">Gender</legend>
	                  <div class="col-sm-10">
	                    <div class="form-check">
	                      <input class="form-check-input" type="radio" name="gender" value="male" checked>
	                      <label class="form-check-label">
	                        Male
	                      </label>
	                    </div>
	                    <div class="form-check">
	                      <input class="form-check-input" type="radio" name="gender" value="female">
	                      <label class="form-check-label">
	                        Female
	                      </label>
	                    </div>
	                    <div class="form-check disabled">
	                      <input class="form-check-input" type="radio" name="gender" value="both" disabled>
	                      <label class="form-check-label">
	                        Both
	                      </label>
	                    </div>
	                  </div>
	                </div>
	              </fieldset>

	             <div class="form-group row">
	                <div class="col-sm-12">
	                  <div class="form-check">
	                    <input class="form-check-input" type="checkbox" name="agree" checked>
	                    <label class="form-check-label" for="agree">
	                      	Agree to Register ? 
	                    </label>
	                  </div>
	                </div>
	              </div>

	              <div class="form-group">
	                <label for="summary">Summary</label>
	                <textarea class="form-control" name="summary" rows="3"></textarea>
	              </div>
	            
		          <button type="submit" class="btn btn-primary">Submit</button>
		          <button type="reset" class="btn btn-primary">Reset</button>
			</form>
{% endblock %}

templates/index.html
<span><a href="">Home</a></span> | 
<span><a href="/admin">Admin</a></span> | 
<span><a href="/blog">First App</a> </span>
<br>
<br>
<br>
<textarea rows="30" cols="150">
Steps
$python -c "import django; print(django.__path__)"
1 - After installation of python, mysql, djadmin( $django-admin startproject project_name )
2 - inside project folder($python manage.py startapp blog)
3 - go to set-ups file{
	ALLOWED_HOSTS for virtual hosting,
	global template path,
	Database server, 
	Email Server
}
4 - migrate the in-built databases
5 - 
6 - create your static and templates folder in project folder
7 - routing of static pages
8 - create one app()
9 - Register your app in main Settings file
10 - include the path in main urls
11 - view.py is your controller
12 - model.py is fetching data to view
13 - forms.py will validation link between database and html form


</textarea>